/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms_gui;

import java.awt.Toolkit;
import sms.other.StudentFrame;
import sms_gui.student.AddStudent;
import sms_gui.student.SearchStudentForm;
/**
 *
 * @author Leshan
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        butAddStudent = new javax.swing.JButton();
        butAddTeacher = new javax.swing.JButton();
        butCreateMarksheet = new javax.swing.JButton();
        butViewMarksheet = new javax.swing.JButton();
        butAddSubjectToTeacher = new javax.swing.JButton();
        butSearchStudent = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        butStudent = new javax.swing.JButton();
        butTeacher = new javax.swing.JButton();
        butSubject = new javax.swing.JButton();
        butNonAcademicStaff = new javax.swing.JButton();
        butGrade = new javax.swing.JButton();
        butMarksheet = new javax.swing.JButton();
        butClass = new javax.swing.JButton();
        butClassTeacher = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Management System");
        setSize(Toolkit.getDefaultToolkit().getScreenSize());

        butAddStudent.setText("Register Student");
        butAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddStudentActionPerformed(evt);
            }
        });

        butAddTeacher.setText("Register Teacher");
        butAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddTeacherActionPerformed(evt);
            }
        });

        butCreateMarksheet.setText("Create Marksheet");
        butCreateMarksheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCreateMarksheetActionPerformed(evt);
            }
        });

        butViewMarksheet.setText("View Marksheet");
        butViewMarksheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butViewMarksheetActionPerformed(evt);
            }
        });

        butAddSubjectToTeacher.setText("Assign Subject to Teacher");
        butAddSubjectToTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddSubjectToTeacherActionPerformed(evt);
            }
        });

        butSearchStudent.setText("Search Student");
        butSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSearchStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butAddStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butAddTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butCreateMarksheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butViewMarksheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butAddSubjectToTeacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butSearchStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(butAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butAddTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butAddSubjectToTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butCreateMarksheet, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butViewMarksheet, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        butStudent.setText("Student");
        butStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStudentActionPerformed(evt);
            }
        });

        butTeacher.setText("Teacher");
        butTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTeacherActionPerformed(evt);
            }
        });

        butSubject.setText("Subject");
        butSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSubjectActionPerformed(evt);
            }
        });

        butNonAcademicStaff.setText("Non-Academic Staff");
        butNonAcademicStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNonAcademicStaffActionPerformed(evt);
            }
        });

        butGrade.setText("Grade");
        butGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGradeActionPerformed(evt);
            }
        });

        butMarksheet.setText("Marksheet");
        butMarksheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMarksheetActionPerformed(evt);
            }
        });

        butClass.setText("Class");
        butClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClassActionPerformed(evt);
            }
        });

        butClassTeacher.setText("Class_Teacher");
        butClassTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClassTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butTeacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butNonAcademicStaff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butMarksheet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butGrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butClassTeacher)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butMarksheet)
                        .addComponent(butGrade)
                        .addComponent(butClass)
                        .addComponent(butClassTeacher))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butStudent)
                        .addComponent(butTeacher)
                        .addComponent(butSubject)
                        .addComponent(butNonAcademicStaff)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("School Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1)))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setBounds(int x, int y, int width, int height) {
        super.setBounds(0,0,Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height); //To change body of generated methods, choose Tools | Templates.
    }

    private void butAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddStudentActionPerformed
        AddStudent s1=new AddStudent();
        jDesktopPane1.add(s1);
        s1.show();// TODO add your handling code here:
    }//GEN-LAST:event_butAddStudentActionPerformed

    private void butAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butAddTeacherActionPerformed

    private void butCreateMarksheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCreateMarksheetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butCreateMarksheetActionPerformed

    private void butViewMarksheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butViewMarksheetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butViewMarksheetActionPerformed

    private void butAddSubjectToTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddSubjectToTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butAddSubjectToTeacherActionPerformed

    private void butStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStudentActionPerformed
        StudentFrame s1=new StudentFrame();
        jDesktopPane1.add(s1);
        s1.show();// TODO add your handling code here:
    }//GEN-LAST:event_butStudentActionPerformed

    private void butTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butTeacherActionPerformed

    private void butSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butSubjectActionPerformed

    private void butNonAcademicStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNonAcademicStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butNonAcademicStaffActionPerformed

    private void butGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butGradeActionPerformed

    private void butMarksheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMarksheetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butMarksheetActionPerformed

    private void butClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butClassActionPerformed

    private void butClassTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClassTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butClassTeacherActionPerformed

    private void butSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSearchStudentActionPerformed
        SearchStudentForm s1=new SearchStudentForm();
        jDesktopPane1.add(s1);
        s1.show();        // TODO add your handling code here:
    }//GEN-LAST:event_butSearchStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAddStudent;
    private javax.swing.JButton butAddSubjectToTeacher;
    private javax.swing.JButton butAddTeacher;
    private javax.swing.JButton butClass;
    private javax.swing.JButton butClassTeacher;
    private javax.swing.JButton butCreateMarksheet;
    private javax.swing.JButton butGrade;
    private javax.swing.JButton butMarksheet;
    private javax.swing.JButton butNonAcademicStaff;
    private javax.swing.JButton butSearchStudent;
    private javax.swing.JButton butStudent;
    private javax.swing.JButton butSubject;
    private javax.swing.JButton butTeacher;
    private javax.swing.JButton butViewMarksheet;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
