/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms_gui.teacher;

/**
 *
 * @author Leshan
 */
public class RemoveTeacherForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public RemoveTeacherForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPane1 = new javax.swing.JPanel();
        butCancel1 = new javax.swing.JButton();
        butRemove = new javax.swing.JButton();
        middlePane3 = new javax.swing.JPanel();
        lblCode2 = new javax.swing.JLabel();
        lblFirstName3 = new javax.swing.JLabel();
        lblLastName3 = new javax.swing.JLabel();
        txtLastName3 = new javax.swing.JTextField();
        txtFirstName3 = new javax.swing.JTextField();
        lblDOB3 = new javax.swing.JLabel();
        txtDOB3 = new javax.swing.JTextField();
        lblAddress10 = new javax.swing.JLabel();
        txtAddress10 = new javax.swing.JTextField();
        lblAddress11 = new javax.swing.JLabel();
        txtAddress11 = new javax.swing.JTextField();
        lblAddress12 = new javax.swing.JLabel();
        txtAddress12 = new javax.swing.JTextField();
        lblMobileNo3 = new javax.swing.JLabel();
        txtMobileNo3 = new javax.swing.JTextField();
        lblTelNo3 = new javax.swing.JLabel();
        txtTelNo3 = new javax.swing.JTextField();
        comboCode2 = new javax.swing.JComboBox();
        butSearch3 = new javax.swing.JButton();
        lblTitle1 = new javax.swing.JLabel();

        buttonPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        butCancel1.setText("Cancel");
        butCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancel1ActionPerformed(evt);
            }
        });

        butRemove.setText("Remove");

        javax.swing.GroupLayout buttonPane1Layout = new javax.swing.GroupLayout(buttonPane1);
        buttonPane1.setLayout(buttonPane1Layout);
        buttonPane1Layout.setHorizontalGroup(
            buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butCancel1)
                .addContainerGap())
        );
        buttonPane1Layout.setVerticalGroup(
            buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPane1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(buttonPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butCancel1)
                    .addComponent(butRemove))
                .addContainerGap())
        );

        middlePane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCode2.setText("Teacher code:");

        lblFirstName3.setText("First Name:");

        lblLastName3.setText("Last Name:");

        txtLastName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastName3ActionPerformed(evt);
            }
        });

        lblDOB3.setText("Date Of Birth:");

        txtDOB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOB3ActionPerformed(evt);
            }
        });

        lblAddress10.setText("Address1:");

        txtAddress10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress10ActionPerformed(evt);
            }
        });

        lblAddress11.setText("Address2:");

        txtAddress11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress11ActionPerformed(evt);
            }
        });

        lblAddress12.setText("Address3:");

        txtAddress12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress12ActionPerformed(evt);
            }
        });

        lblMobileNo3.setText("Mobile No. :");

        txtMobileNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileNo3ActionPerformed(evt);
            }
        });

        lblTelNo3.setText("Tel no.(Home):");

        txtTelNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelNo3ActionPerformed(evt);
            }
        });

        comboCode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCode2ActionPerformed(evt);
            }
        });

        butSearch3.setText("Search");

        javax.swing.GroupLayout middlePane3Layout = new javax.swing.GroupLayout(middlePane3);
        middlePane3.setLayout(middlePane3Layout);
        middlePane3Layout.setHorizontalGroup(
            middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(middlePane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMobileNo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddress11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddress10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDOB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLastName3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCode2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAddress12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTelNo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFirstName3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addComponent(txtDOB3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAddress10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAddress11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAddress12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMobileNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLastName3))
                    .addGroup(middlePane3Layout.createSequentialGroup()
                        .addComponent(comboCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butSearch3)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        middlePane3Layout.setVerticalGroup(
            middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(middlePane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCode2)
                    .addComponent(comboCode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butSearch3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName3)
                    .addComponent(txtFirstName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName3)
                    .addComponent(txtLastName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB3)
                    .addComponent(txtDOB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress10)
                    .addComponent(txtAddress10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress11)
                    .addComponent(txtAddress11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress12)
                    .addComponent(txtAddress12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelNo3)
                    .addComponent(txtTelNo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(middlePane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobileNo3)
                    .addComponent(txtMobileNo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblTitle1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("REMOVE TEACHER");
        lblTitle1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(middlePane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(middlePane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(buttonPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butCancel1ActionPerformed

    private void txtLastName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastName3ActionPerformed

    private void txtDOB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOB3ActionPerformed

    private void txtAddress10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress10ActionPerformed

    private void txtAddress11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress11ActionPerformed

    private void txtAddress12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress12ActionPerformed

    private void txtMobileNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileNo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNo3ActionPerformed

    private void txtTelNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelNo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelNo3ActionPerformed

    private void comboCode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCode2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCancel1;
    private javax.swing.JButton butRemove;
    private javax.swing.JButton butSearch3;
    private javax.swing.JPanel buttonPane1;
    private javax.swing.JComboBox comboCode2;
    private javax.swing.JLabel lblAddress10;
    private javax.swing.JLabel lblAddress11;
    private javax.swing.JLabel lblAddress12;
    private javax.swing.JLabel lblCode2;
    private javax.swing.JLabel lblDOB3;
    private javax.swing.JLabel lblFirstName3;
    private javax.swing.JLabel lblLastName3;
    private javax.swing.JLabel lblMobileNo3;
    private javax.swing.JLabel lblTelNo3;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JPanel middlePane3;
    private javax.swing.JTextField txtAddress10;
    private javax.swing.JTextField txtAddress11;
    private javax.swing.JTextField txtAddress12;
    private javax.swing.JTextField txtDOB3;
    private javax.swing.JTextField txtFirstName3;
    private javax.swing.JTextField txtLastName3;
    private javax.swing.JTextField txtMobileNo3;
    private javax.swing.JTextField txtTelNo3;
    // End of variables declaration//GEN-END:variables
}
